import { useRef, useState } from "react";

const DropdownInput = ({ title }) => {
    const inputRef = useRef(null);
    const buttonRef = useRef(null);
    const [value, setValue] = useState("");

    const handleFocus = () => {
        inputRef.current.focus();
        buttonRef.current.classList.add("border-[3px]");
        buttonRef.current.classList.add("border-blue-600");

        //  buttonRef.current.focus();
    };

    return (
        <div>
            {/* <div
                class="styles_dropdown__gnPVg styles_isOpen__EQ6WZ"
                role="listbox"
            >
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Austria
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Belgium
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Bulgaria
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Croatia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Cyprus
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Czech Republic
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Denmark
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Estonia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Finland (mainland)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    France (mainland)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Germany
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Greece
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Hungary
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Ireland
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Italy
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Latvia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Lithuania
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Luxembourg
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Netherlands (mainland)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Poland
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Portugal (Madeira &amp; Azores)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Portugal (mainland)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Romania
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Slovakia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Slovenia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Spain (Balearic Islands - Ibiza Majorca Minorca)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Spain (mainland)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Sweden
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Norway
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Switzerland
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    United Kingdom (mainland)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Afghanistan
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Finland (Aland Islands)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Albania
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Algeria
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    American Samoa
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Andorra
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Angola
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Anguilla
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Antarctica
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Antigua and Barbuda
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Argentina
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Armenia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Aruba
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Australia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Azerbaijan
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Bahamas
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Bahrain
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Bangladesh
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Barbados
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Belize
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Benin
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Bermuda
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Bhutan
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Bolivia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Netherlands (Bonaire)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Bosnia and Herzegovina
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Botswana
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Bouvet Island
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Brazil
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    British lndian Ocean Territory
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    British Virgin Islands
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Brunei
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Burkina Faso
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Burundi
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Cabo Verde
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Cambodia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Cameroon
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Canada
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Spain (Canary Islands - Atlantic ocean)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Cayman Islands
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Central African Republic
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Chad
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Chile
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    China
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Christmas Island
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Cocos (Keeling) Islands
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Colombia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Comoros
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Congo
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Cook Islands
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Costa Rica
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Cuba
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Curacao
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Democratic Republic of the Congo
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Djibouti
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Dominica
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Dominican Republic
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Ecuador
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Egypt
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    El Salvador
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Equatorial Guinea
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Eritrea
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Eswatini
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Ethiopia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Falkland Islands
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Faroe Islands
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Fiji
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    French Guiana (France)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    French Polynesia (France)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    French Southern Territories
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Gabon
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Gambia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Georgia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Ghana
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Gibraltar
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Greenland
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Grenada
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Guadeloupe (France)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Guam
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Guatemala
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    United Kingdom (Guernsey)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Guinea
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Guinea-Bissau
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Guyana
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Haiti
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Heard and Mc Donald Islands
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Honduras
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Hong Kong
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Iceland
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    India
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Indonesia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Iran
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Iraq
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    United Kingdom (Isle of Man)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Israel
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Ivory Coast
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Jamaica
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Japan
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    United Kingdom (Jersey)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Jordan
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Kazakhstan
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Kenya
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Kiribati
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Kosovo
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Kuwait
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Kyrgyzstan
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Laos
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Lebanon
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Lesotho
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Liberia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Libya
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Liechtenstein
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Macau
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Madagascar
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Malawi
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Malaysia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Maldives
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Mali
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Malta
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Marshall Islands
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Martinique (France)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Mauritania
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Mauritius
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Mayotte (France)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Mexico
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Micronesia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Moldova
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Monaco
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Mongolia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Montenegro
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Montserrat
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Morocco
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Mozambique
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Myanmar
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Namibia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Nauru
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Nepal
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    New Caledonia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    New Zealand
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Nicaragua
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Niger
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Nigeria
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Niue
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Norfork Island
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    North Macedonia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Northern Mariana Islands
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Oman
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Pakistan
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Palau
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Panama
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Papua New Guinea
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Paraguay
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Peru
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Philippines
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Pitcairn
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Puerto Rico
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Qatar
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Reunion (France)
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Rwanda
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Saint Barthelemy
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Saint Helena
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Saint Kitts and Nevis
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Saint Lucia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Saint Pierre and Miquelon
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Saint Vincent and the Grenadines
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Samoa
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    San Marino
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Sao Tome and Principe
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Saudi Arabia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Senegal
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Serbia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Seychelles
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Sierra Leone
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Singapore
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Sint Maarten
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Solomon Islands
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Somalia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    South Africa
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    South Georgia and the South Sandwich Islands
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    South Korea
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    South Sudan
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Sri Lanka
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    State of Palestine
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Sudan
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Suriname
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Svalbard and Jan Mayen
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Syria
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Taiwan
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Tajikistan
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Tanzania
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Thailand
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Timor-Leste
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Togo
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Tokelau
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Tonga
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Trinidad and Tobago
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Tunisia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Turkey
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Turkmenistan
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Turks and Caicos Islands
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Tuvalu
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Uganda
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    United Arab Emirates
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    United States
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    United States Minor Outlying Islands
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    United States Virgin Islands
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Uruguay
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Uzbekistan
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Vanuatu
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Vatican City
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Venezuela
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Vietnam
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Wallis and Futuna
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Western Sahara
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Yemen
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Zambia
                </div>
                <div
                    tabindex="0"
                    role="option"
                    aria-selected="false"
                    class="styles_dropdownItem__iR47z"
                >
                    Zimbabwe
                </div>
            </div> */}
        </div>
    );
};

export default DropdownInput;

{
    /* <div>
<button ref={buttonRef} className="w-full bg-white rounded-xl focus:border-[3px]  py-4 px-4 focus:border-blue-600 " type="button" data-bs-toggle="dropdown" aria-expanded="false" onClick={handleFocus}>
    <div
        htmlFor=""
        className="flex flex-col justify-start text-black font-black text-xl text-start"
    >
        {title}
        <input
        ref={inputRef}
        type="text"
        value={value}
        onChange={(e) => setValue(e.target.value)}
        placeholder="Type to search"
        className="!outline-none text-xl text-blue-600 cursor-pointer font-bold py-1"
        
    />
    </div>

   
</button>
<ul className="dropdown-menu">

</ul>
</div> */
}
